config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do


  use_doorkeeper
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "users", only: [:create] do
    resource :password,
             controller: "clearance/passwords",
             only: [:create, :edit, :update]
  end

  resources :events do
    resources :comments, only: [:new, :create, :destroy]
    resources :documents, only: [:show, :create, :new, :destroy]
    resources :invites, only: [:new, :create]
  end

  resources :notifications, only: %i{index show}
  root 'events#index'
  mount Sidekiq::Web, at: '/sidekiq'

  namespace :api, path: "api" do
    get 'user', to: "users#show"
    post 'authenticate', to: 'authentication#authenticate'
    resources :users, only: [:create]
    resources :events do
      resources :comments, only: [:new, :create, :destroy]
      resources :documents, only: [:show, :create, :new, :destroy]
      resources :invites, only: [:new, :create]
    end
  end
end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :event
  belongs_to :user

  validates :body, presence: true, length: {minimum: 2}


end

app/controllers/api/comments_controller.rb
class API::CommentsController < API::ApplicationController
  load_and_authorize_resource :event
  load_and_authorize_resource :comment, :through => :event, :shallow => true
  before_action :set_comment, only: [:destroy]
  before_action :set_event, only: [:create]


  def create
    @comment=@event.comments.build(comment_params)
    @comment.user_id=current_user.id
    respond_to do |format|
      if @comment.save
        format.json { render json: @comment }
      else
        format.json { render json: @comment.errors }
      end
    end
  end

  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to :back, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_comment
    @comment = Comment.find(params[:id])
  end

  def set_event
    @event=Event.find(params[:event_id])
  end

  def comment_params
    params.permit(:body)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  load_and_authorize_resource :event
  load_and_authorize_resource :comment, :through => :event, :shallow => true
  before_action :set_comment, only: [:destroy]

  def new
    @event=Event.find(parms[:event])
    @comment=@event.comments.build
  end

  def create
    @event=Event.find(params[:event_id])
    @comment=@event.comments.build(comment_params)
    @comment.user_id=current_user.id
    respond_to do |format|
      if @comment.save

        format.html { redirect_to @event, notice: 'Comment was successfully created.' }
      else
        format.html { redirect_to @event, alert: 'Comment cant be blank.' }
      end
    end
  end

  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to :back, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_comment
    @comment = Comment.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div class="card">

          <%= message.body %>

</div>

app/views/comments/_comments.html.erb
<% if event.comments.any? %>

    <div class="message">
      <h3>All comments</h3>
      <% event.comments.each do |comment| %>
          <% if comment.user.present? %>

              <p>
                <h4>
                  <i class="fa fa-male" aria-hidden="true"> <%= comment.user.email %></i>
              <p>Comment: <%= comment.body %><p>
              <p><%= link_to "Delete Comment", event_comment_path(comment), method: :delete,
                             data: {confirm: "Are you sure you want to delete this ticket?"},
                             class: "btn btn-warning btn-xs" %></p>
              </h4>

              </p>
          <% end %>
      <% end %>
    </div>
<% end %>

app/views/comments/_form.html.erb
<%= simple_form_for([event, event.comments.build]) do |f| %>
    <%= f.error_notification %>
    <%= f.label :comment %>
    <div class="form-inputs">

      <%= f.text_area :body %>
    </div>
    <%= f.submit "Post",  class: "new" %>
<% end %>