config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do


  use_doorkeeper
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "users", only: [:create] do
    resource :password,
             controller: "clearance/passwords",
             only: [:create, :edit, :update]
  end

  resources :events do
    resources :comments, only: [:new, :create, :destroy]
    resources :documents, only: [:show, :create, :new, :destroy]
    resources :invites, only: [:new, :create]
  end

  resources :notifications, only: %i{index show}
  root 'events#index'
  mount Sidekiq::Web, at: '/sidekiq'

  namespace :api, path: "api" do
    get 'user', to: "users#show"
    post 'authenticate', to: 'authentication#authenticate'
    resources :users, only: [:create]
    resources :events do
      resources :comments, only: [:new, :create, :destroy]
      resources :documents, only: [:show, :create, :new, :destroy]
      resources :invites, only: [:new, :create]
    end
  end
end

app/models/notification.rb
class Notification < ApplicationRecord
  validates :event_id, uniqueness: {scope: :attached_user_id}
  belongs_to :invite
  belongs_to :event
  belongs_to :attached_user, class_name: 'User'
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  def show
    notification = Notification.find(params[:id])
    event=Event.find(notification.event_id)
    AttachedEventsUser.create(user_id: current_user.id, event_id: event.id)
    redirect_url = params[:redirect_url]
    if notification.delete && redirect_url.present?
      redirect_to redirect_url
    end
  end

  def index
    @notifications = current_user.notifications
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/_notifications_nav.html.erb
<% if @notifications.present? %>
    <%= link_to "You have #{@notifications.count} notifications", notifications_path %>
<% end %>

app/views/notifications/index.erb
<h2>Invites</h2>
<div class="attachments">
  <% @notifications.each do |notification| %>
      <header>
        <p>
        <h4>Event link, click to
          go: <%= link_to notification.event.description, notification_path(notification.id, redirect_url: event_path(notification.event.id)) %> </h4>
        </p>
      </header>
  <% end %>
</div>