config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do


  use_doorkeeper
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "users", only: [:create] do
    resource :password,
             controller: "clearance/passwords",
             only: [:create, :edit, :update]
  end

  resources :events do
    resources :comments, only: [:new, :create, :destroy]
    resources :documents, only: [:show, :create, :new, :destroy]
    resources :invites, only: [:new, :create]
  end

  resources :notifications, only: %i{index show}
  root 'events#index'
  mount Sidekiq::Web, at: '/sidekiq'

  namespace :api, path: "api" do
    get 'user', to: "users#show"
    post 'authenticate', to: 'authentication#authenticate'
    resources :users, only: [:create]
    resources :events do
      resources :comments, only: [:new, :create, :destroy]
      resources :documents, only: [:show, :create, :new, :destroy]
      resources :invites, only: [:new, :create]
    end
  end
end

app/models/event.rb
class Event < ApplicationRecord
  include PgSearch
  belongs_to :user
  has_many :attached_events_users
  has_many :attached_users, through: :attached_events_users, source: :user
  has_many :invites
  has_many :documents, -> { order("created_at DESC").limit(3) }
  has_many :comments, -> { order("created_at DESC").limit(3) }
  has_many :notifications
  pg_search_scope :search_everywhere, against: [:time]
  validates :place, presence: true, length: {minimum: 3, maximum: 40}
  validates :description, presence: true, length: {minimum: 5, maximum: 100}

  validates :time,
            date: {after: Proc.new { Time.now },
                   before: Proc.new { Time.now + 1.year }}
  validates :end_time,
            date: {after: :time}


end

app/controllers/api/events_controller.rb
class API::EventsController < API::ApplicationController
  load_and_authorize_resource
respond_to :json
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  def index


    if params[:due]
      time=params[:due]
      events=current_user.events.search_everywhere(time)
      attached=current_user.attached_events.search_everywhere(time)
      respond_to do |format|
        format.json { render json: events+attached }
      end

    elsif params[:interval]
      interval=params[:interval].scan(/\d/).join('').to_i
      events=current_user.events.where(time: Time.now..(Time.now+interval.day))
      attached=current_user.attached_events.where(time: Time.now..(Time.now+interval.day))
      respond_to do |format|
        format.json { render json: events+attached }
      end
    else
      events=current_user.events
      attached=current_user.attached_events
      render json: events+attached
    end
  end


  def show

   render json: @event

  end

  def new
    @event = Event.new
  end

  def edit
  end

  def create
    @event = current_user.events.create(event_params)
    respond_to do |format|
      if @event.save
        format.json { render json: @event }
      else
        format.json { render json: @event.errors }
      end
    end
  end


  def update
    respond_to do |format|
      if @event.update(event_params)
        format.json { render @event, status: :ok }
      else
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @event.destroy
    respond_to do |format|
      format.json { head :no_content }
    end
  end

  protected


  private
  def set_event
    @event=Event.find(params[:id])
  end

  def event_params
    params.permit(:event, :place, :time, :description, :end_time)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  load_and_authorize_resource
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  def index
    if params[:due]
      time=params[:due]
      @events = current_user.events.search_everywhere(time)
      @attached = current_user.attached_events.search_everywhere(time)
    elsif params[:interval]
      interval=params[:interval].scan(/\d/).join('').to_i
      @events = current_user.events.where(time: Time.now..(Time.now+interval.day))
      @attached = current_user.attached_events.where(time: Time.now..(Time.now+interval.day))
    else
      @events = current_user.events
      @attached = current_user.attached_events
    end
  end


  def show
  end

  def new

  end

  def edit
  end

  def create
    @events
    @event = current_user.events.create(event_params)
    respond_to do |format|
      if @event.save
        format.html { redirect_to events_url, notice: 'Event was successfully created.' }
        format.js
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:place, :time, :description, :end_time)
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_attached.html.erb
<table id="attached">
  <thead>
  <tr class="warning">
    <th><h4>Info</h4></th>
    <th><h4>Place</h4></th>
    <th><h4>Time</h4></th>
    <th><h4>Description</h4></th>

  </tr>
  </thead>

  <tbody>
  <% attached.each do |event| %>
      <tr class="active">
        <td><%=link_to 'More Info', event_path(event),class: "new" %></td>
        <td><h4><%= event.place %></h4></td>
        <td><h4><%= event.time.localtime.strftime("%d %b. %Y %H:%M") if event.time.present? %></h4></td>
        <td><h4><%= event.description%></h4></td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/events/_events.html.erb
<table id="attributes">
  <thead>
  <tr class="warning">
    <th><h4>Info</h4></th>
    <th><h4>Place</h4></th>
    <th><h4>Time</h4></th>
    <th><h4>Description</h4></th>

  </tr>
  </thead>

  <tbody>
  <% events.each do |event| %>
      <tr class="active">
        <td><%=link_to 'More Info', event_path(event),class: "new" %></td>
        <td><h4><%= event.place %></h4></td>
        <td><h4><%= event.time.localtime.strftime("%d %b. %Y %H:%M") if event.time.present? %></h4></td>
        <td><h4><%= event.description%></h4></td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/events/_form.html.erb
<div class="container-fluid">
  <div class="span12 centered-text">
<%= simple_form_for @event, remote: true do |f| %>
    <% if @event.errors.any? %>
        <% @event.errors.full_messages.each do |message| %>

            <div class="alert alert-alert">
              <li><%= message %></li>
            </div>
        <% end %>

    <% end %>

    <% if f.error_notification.present? %>
        <div class="alert alert-alert">
          <%= f.error_notification %>
        </div>
    <% end %>


    <div class="form-group row">
      <div class="col-10">
        <%= f.label :place, for: "example-text-input", class: "col-2 col-form-label" %>
        <%= f.text_field :place, class: "form-control", name:"place" %>

      </div>
    </div>

    <div class="form-group row">
      <div class="col-10">
        <%= f.label :start_time %>
        <%= f.datetime_select :time %>
      </div>
    </div>

    <div class="form-group row">
      <div class="col-10">
        <%= f.label :end_time %>
        <%= f.datetime_select :end_time %>
      </div>
    </div>


    <div class="form-group row">
      <div class="col-10">
        <%= f.label :description, for: "example-text-input", class: "col-2 col-form-label" %>
        <%= f.text_area :description, class: "form-control",name:"description" %>
      </div>
    </div>


    <div class="form-group row">
      <div class="col-10">
        <%= f.button :submit, "Create", class: "btn btn-primary btn-sm" %>
      </div>
    </div>
<% end %>
</div>
</div>

app/views/events/application.html.erb
<!DOCTYPE html>
<html ng-app>
<head>
  <title>
    <% if content_for?(:title) %>
        <%= yield(:title) %>
    <% else %>
        EventSystem
    <% end %>
  </title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>

  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<body>
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <%= link_to "EventsSystem", root_path, class: "navbar-brand" %>
      <button type="button" class="navbar-toggle collapsed"
              data-toggle="collapse" data-target="#collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="collapse navbar-collapse" id="collapse">
      <ul class="nav navbar-nav">
        <li class="<%= "active" if current_page?("/") %>">
          <%= link_to "Home", root_path %>
        </li>

        <% unless user_signed_in? %>
            <li class="<%= "active" if current_page?("/users/sign_up") %>">
              <%= link_to "Sign up", new_user_registration_path %>
            </li>
            <li class="<%= "active" if current_page?("/users/sign_in") %>">
              <%= link_to "Sign in", sign_in_path %>
            </li>
        <% end %>

        <% if user_signed_in? %>
            <div class="navbar-right">
              <p class="navbar-text" id="signed" onclick="onClick('<%= current_user.email %>')" >
                Signed in as <%= current_user.email %>
              </p>
              <ul class="nav navbar-nav">
                <li><%= link_to "Sign out", sign_out_path, :method => :delete %>
                </li>
                <li>
                  <%= render partial: 'notifications/notifications_nav' %>
                </li>
              </ul>
            </div>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

<div class="container">
  <% flash.each do |key, message| %>
      <div class="alert alert-<%= key %>">
        <%= message %>
      </div>
  <% end %>

  <%= yield %>
</div>
</body>
</html>

app/views/events/create.js.erb
$('#new_event').remove();
$('#event_new').show();
$( "#attributes" ).load( "<%= events_url %> #attributes");

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event, class: "btn btn-warning btn-sm" %>
<%= link_to 'Back', events_path, class: "btn btn-warning btn-sm" %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>
<%= link_to 'Create new event', new_event_path,id:"event_new", class: "new",remote: true %>

<h1>Your Events</h1>

<%= render partial:'events/events',locals: {events:@events} %>

<br>



<h1>Event in which you are a member</h1>
<%= render partial:'events/attached',locals: {attached:@attached} %>

<br>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path, class: "btn btn-warning btn-sm"%>

app/views/events/new.js.erb
$('#event_new').hide().after('<%=j render partial:"form" %>');

app/views/events/show.html.erb
<div id="event">
  <div id="invite">
    <p>
    <h3>Send Invite to event:</h3>
    <%= render partial: "invites/form", locals: {event: @event} %>
    <p>
  </div>
  <header>
    <table id="attributes">
      <tr>
        <th>Author:</th>
        <td><%= @event.user.email %></td>
      </tr>
      <tr>
        <th>Created:</th>
        <td><%= time_ago_in_words(@event.created_at) %> ago</td>
      </tr>
    </table>

    <h3>Description: <%= @event.description %>
      <h3>Place: <%= @event.place %></h3>
      <h4>Start Time: <%= @event.time.localtime.strftime("%d %b. %Y %H:%M") %> </h4>
      <h4>End Time: <%= @event.end_time.localtime.strftime("%d %b. %Y %H:%M") %> </h4>
      <ul class="actions">
        <li><%= link_to "Edit Event", edit_event_path(@event),
                        class: "edit" %></li>
        <li><%= link_to "Delete Event", @event, method: :delete,
                        data: {confirm: "Are you sure you want to delete this ticket?"},
                        class: "delete" %></li>
      </ul>
  </header>
  <% if @event.documents.any? %>
      <h4>Attachments</h4>
      <div class="attachments">
        <% @event.documents.each do |document| %>
            <p><%= link_to "Delete Document", event_document_url(document),
                           method: :delete,
                           data: {confirm: "Are you sure you want to delete this ticket?"},
                           class: "btn btn-warning btn-xs" %></p>
            <%="#{document.name}:"%> <%= link_to File.basename(document.attachment.url),
                        event_document_path(document.id) %>
            (<%= number_to_human_size(document.attachment.size) %>)

            </p>
        <% end %>
      </div>
  <% end %>
  <p>
    <%= render partial: "documents/form", locals: {event: @event} %>
  </p>
</div>
<header>
</header>


<div id="message">
  <h3> <%= render partial: "comments/form", locals: {event: @event} %></h3>
</div>


<div id="messages" data-event-id="<%= @event.id %>">
  <h3> <%= render partial: "comments/comments", locals: {event: @event} %></h3>
</div>